name = "The Highland Park Space Co."
license = "Apache License 2.0"
licenselink = "//github.com/digitalcraftsman/hugo-agency-theme/blob/master/LICENSE"
description = "Deliverying creative solutions for your space and science needs."
homepage = "//hpspace.github.io"
tags = ["portfolio", "company", "contact form", "clients", "team"]
features = ["portfolio with modals", "contact form", "timeline"]
min_version = 0.14

[author]
  name = "hpspace"
  homepage = "//hpspace.github.io"

# If porting an existing theme
[original]
  name = "David Miller"
  homepage = "//www.ironsummitmedia.com/"
  repo = "//github.com/IronSummitMedia/startbootstrap-agency"
