baseurl = "https://hpspace.github.io/"
languageCode = "en-us"
title = "The Highland Park Space Company"
theme = "creative"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
  # information about you and your website.
	name = "The Highland Park Space Company"
	description = "A space and science consulting firm for creatives"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "The Highland Park Space Co."

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "A creative solution for your epic space ideas"
		subtitle   = "**The Highland Park Space Company** is a scientific consulting firm for entertainment and production industries, providing creative solutions for imagining complex scientific concepts in space technology and science fiction."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "Bridging the gap between fiction and reality requires an expertise that only space technologists have. **HPSpaceCo** provides a personalized scientific and space technology consulting experience, working directly with you and your team on your difficult concepts."
		buttonText  = "Get started!"


	# Service section
  # Use font icons at http://fortawesome.github.io/Font-Awesome/icons/
	[params.services]
		headline = "We're at your service!"

    [[params.services.list]]
      icon = "fa-pencil-square-o"
      title = "Script/Media Ideas"
      description = "Re-write, technical dialogue, and jargon suggestions, we can work with your team to develop your script."

    [[params.services.list]]
      icon = "fa-lightbulb-o"
      title = "Brainstorming Session"
      description = "Have a personal, one-on-one/team ideation and brainstorming session -- space technology on-the-fly!"

    [[params.services.list]]
      icon = "fa-newspaper-o"
      title = "Up to Date"
      description = "Sign up for ours newsletter to learn about new happenings in space technology and science fiction."

    [[params.services.list]]
      icon = "fa-smile-o"
      title = "Friendly People"
      description = "We're just your friendly neighborhood space company!"


  # Portfolio modals
	[params.portfolio]
    headline = "Here's some fun stuff we've worked on!"

	[params.portfolio.modal]
    client = "Client"
    date = "Date"
    category = "Category"
    buttonText = "Close"

  # Aside section
	[params.aside]
    headline = "Let us turn your crazy space ideas into actual scientific concepts."
  #  headline = "Interested in a newsletter on space technology and science fiction?"
  #  text = "Yeah, us to. Click below to be added to our newsletter!"

  #[params.aside.button]
  #  text = "Sign Up!"
  #  link = "/#contact"

	# Contact section
	[params.contact]
		headline = "Get In Touch With Us!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "949-682-5469"
		email = "info@hpspace.co"
